### Pedindo Ajuda

In [1]:
help.start()

starting httpd help server ...
 done



If nothing happens, you should open
'http://127.0.0.1:28493/doc/html/index.html' yourself


In [2]:
help("pprint")

In [4]:
??pprint

In [5]:
help.search("pprint")

## Diretório de trabalho

In [6]:
getcwd()

ERROR: Error in getcwd(): não foi possível encontrar a função "getcwd"


In [1]:
dir()

[1] "0 - Preparação dos dados" "Aprendizado de máquina"  
[3] "Atividade Desafio"        "Aula R.ipynb"            
[5] "Plotly.ipynb"             "school_earnings.csv"     
[7] "venv"

In [ ]:
choose.dir()

In [14]:
list.files()

[1] "0 - Preparação dos dados" "Aprendizado de máquina"  
[3] "Atividade Desafio"        "Aula R.ipynb"            
[5] "aula1.RData"              "Plotly.ipynb"            
[7] "school_earnings.csv"      "venv"

In [3]:
ls()

character(0)

In [4]:
x<-0

In [5]:
ls()

[1] "x"

In [6]:
objects()

[1] "x"

In [7]:
y=10

In [17]:
objects()

character(0)

In [10]:
y

[1] 10

In [149]:
save.image(file="aula3.RData")

In [15]:
rm(x)

In [16]:
rm(y)

In [18]:
load(file="aula3.RData")

In [19]:
objects()

[1] "x" "y"

### Trabalhando com pacotes

In [20]:
library()

In [21]:
install.packages("ggplot2")

Installing package into 'C:/Users/edson/OneDrive/Documentos/R/win-library/3.6'
(as 'lib' is unspecified)



package 'ggplot2' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\edson\AppData\Local\Temp\RtmpGSj3Ks\downloaded_packages


In [22]:
library(ggplot2)

### Leitura de dados

In [147]:
dados_table <- read.table("school_earnings.csv", header=TRUE, sep=",")

In [148]:
dados_table

School     Women Men Gap
1  MIT         94   152 58 
2  Stanford    96   151 55 
3  Harvard    112   165 53 
4  U.Penn      92   141 49 
5  Princeton   90   137 47 
6  Chicago     78   118 40 
7  Georgetown  94   131 37 
8  Tufts       76   112 36 
9  Yale        79   114 35 
10 Columbia    86   119 33 
11 Duke        93   124 31 
12 Dartmouth   84   114 30 
13 NYU         67    94 27 
14 Notre Dame  73   100 27 
15 Cornell     80   107 27 
16 Michigan    62    84 22 
17 Brown       72    92 20 
18 Berkeley    71    88 17 
19 Emory       68    82 14 
20 UCLA        64    78 14 
21 SoCal       72    81  9

### Sequências

In [28]:
1:10

[1]  1  2  3  4  5  6  7  8  9 10

In [30]:
(1:10)*10

[1]  10  20  30  40  50  60  70  80  90 100

In [31]:
seq(from=0, to=100, by=10)

[1]   0  10  20  30  40  50  60  70  80  90 100

In [32]:
rep("A", times=10)

[1] "A" "A" "A" "A" "A" "A" "A" "A" "A" "A"

In [33]:
rep(c("A","B","C"), times=10)

[1] "A" "B" "C" "A" "B" "C" "A" "B" "C" "A" "B" "C" "A" "B" "C" "A" "B" "C" "A"
[20] "B" "C" "A" "B" "C" "A" "B" "C" "A" "B" "C"

In [34]:
rep(c("A","B","C"), each=10)

[1] "A" "A" "A" "A" "A" "A" "A" "A" "A" "A" "B" "B" "B" "B" "B" "B" "B" "B" "B"
[20] "B" "C" "C" "C" "C" "C" "C" "C" "C" "C" "C"

In [38]:
seqABC <- rep(c("A","B","C"), times=c(2,3,5))

In [39]:
seqABC

[1] "A" "A" "B" "B" "B" "C" "C" "C" "C" "C"

### Trabalhando com Datas

In [40]:
copa.70 <- "21/06/70"

In [41]:
copa.94 <- "17/07/94"

In [42]:
copa.94 - copa.70

ERROR: Error in copa.94 - copa.70: argumento não-numérico para operador binário


In [43]:
class(copa.94); class(copa.70)

[1] "character"

[1] "character"

In [44]:
copa.70 <- as.Date(copa.70,format="%d/%m/%y")

In [46]:
copa.94 <- as.Date(copa.94,format="%d/%m/%y")

In [47]:
class(copa.94); class(copa.70)

[1] "Date"

[1] "Date"

In [83]:
res <- difftime(copa.94, copa.70,units="weeks")

### Conversão de Tipos

In [57]:
class(res)

[1] "difftime"

In [58]:
typeof(copa.94)

[1] "double"

In [59]:
is.integer(copa.94)

[1] FALSE

### Criação de Objetos

In [62]:
a = 1:5; a

[1] 1 2 3 4 5

In [63]:
b = factor(rep(c("a","b","c"), each=3)); b

[1] a a a b b b c c c
Levels: a b c

In [64]:
c = data.frame(sec=c("XIX", "XX", "XXI"), inicio=c(1801,1901,2001)); c

sec inicio
1 XIX 1801  
2 XX  1901  
3 XXI 2001

In [65]:
d = matrix(round(runif(40,0,100)), ncol=8); d

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 56   59   79   63   76   52    9   79  
[2,] 85   46   67    3   34   12   59   94  
[3,] 10   61   21   24    6   49   93   74  
[4,]  8   48   81   19    8   68   90   31  
[5,] 93   19   48   90   68   30    2   44

In [66]:
e = array(1:12, c(3,2,2)); e

, , 1

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

, , 2

     [,1] [,2]
[1,]    7   10
[2,]    8   11
[3,]    9   12

In [69]:
minha.lista = list(um.vetor=a, um.fator = b, um.data.frame=c, uma.matriz=d)

In [71]:
str(minha.lista)

List of 4
 $ um.vetor     : int [1:5] 1 2 3 4 5
 $ um.fator     : Factor w/ 3 levels "a","b","c": 1 1 1 2 2 2 3 3 3
 $ um.data.frame:'data.frame':	3 obs. of  2 variables:
  ..$ sec   : Factor w/ 3 levels "XIX","XX","XXI": 1 2 3
  ..$ inicio: num [1:3] 1801 1901 2001
 $ uma.matriz   : num [1:5, 1:8] 56 85 10 8 93 59 46 61 48 19 ...


In [72]:
minha.lista$um.data.frame

sec inicio
1 XIX 1801  
2 XX  1901  
3 XXI 2001

In [73]:
length(b)

[1] 9

In [74]:
length(minha.lista)

[1] 4

In [75]:
dim(minha.lista$um.data.frame)

[1] 3 2

In [78]:
nrow(d); ncol(d)

[1] 5

[1] 8

### Indexando e Acessando Itens

- O operador [] sempre retornar um objeto da mesma classe que o original.

- O operador [[]] é usado para extrair os elementos de uma lista ou data frame.

- O operador $ é usado para extrair elementos nomeados de uma lista ou data frame.

In [89]:
cont <- c(8, 4, NA, 9, 6, 1, 7, 9)

In [90]:
cont[4]

[1] 9

In [92]:
cont[c(1,4,8)]

[1] 8 9 9

In [93]:
cont[-c(1,4,8)]

[1]  4 NA  6  1  7

In [94]:
cont[1:5]

[1]  8  4 NA  9  6

In [95]:
cont[is.na(cont)]

[1] NA

In [96]:
cont[!is.na(cont)]

[1] 8 4 9 6 1 7 9

In [97]:
is.na(cont)

[1] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE

In [99]:
mat <- matrix(1:9, nrow=3);mat

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [100]:
mat[2,3]

[1] 8

In [101]:
mat[,1]; mat[1,]

[1] 1 2 3

[1] 1 4 7

In [102]:
mat[c(1,3), c(2,3)]

[,1] [,2]
[1,] 4    7   
[2,] 6    9

In [104]:
colnames(mat)<-LETTERS[1:3]

In [105]:
mat

A B C
[1,] 1 4 7
[2,] 2 5 8
[3,] 3 6 9

In [106]:
mat[,"B"]

[1] 4 5 6

In [107]:
rownames(mat) <- LETTERS[24:26]

In [108]:
mat

A B C
X 1 4 7
Y 2 5 8
Z 3 6 9

In [109]:
da <- data.frame(A = 4:1, B = c(2, NA, 5, 8))


In [110]:
da

A B 
1 4  2
2 3 NA
3 2  5
4 1  8

In [111]:
da[2,1]

[1] 3

In [112]:
da$A

[1] 4 3 2 1

In [113]:
da$B[3]

[1] 5

In [116]:
x<-da[is.na(da$A)]

In [117]:
x

1
2
3
4

In [118]:
y<-da[is.na(da$B)]

In [119]:
y

B 
1  2
2 NA
3  5
4  8

In [129]:
dados <-c(5,15,42,28,79,4,7,14)

In [122]:
dados>15

[1] FALSE FALSE  TRUE  TRUE  TRUE FALSE FALSE FALSE

In [123]:
dados[dados>15]

[1] 42 28 79

In [124]:
dados[dados>15 & dados < 35]

[1] 28

In [125]:
cara <- letters[1:length(dados)]


In [126]:
cara

[1] "a" "b" "c" "d" "e" "f" "g" "h"

In [131]:
dados[cara %in% c("a", "c")]


[1]  5 42

In [132]:
dados <- data.frame(ano = c(2001, 2002, 2003, 2004, 2005),
captura = c(26, 18, 25, 32, NA),
porto = c("SP", "RS", "SC", "SC", "RN"))


In [133]:
dados

ano  captura porto
1 2001 26      SP   
2 2002 18      RS   
3 2003 25      SC   
4 2004 32      SC   
5 2005 NA      RN

1- dados do ano de 2004


In [134]:
subset(dados, dados$ano==2004)

ano  captura porto
4 2004 32      SC

In [141]:
dados[dados$ano ==2004,]

ano  captura porto
4 2004 32      SC

2- dados do porto de SC

In [135]:
subset(dados, dados$porto=="SC")

ano  captura porto
3 2003 25      SC   
4 2004 32      SC

In [142]:
dados[dados$porto =="SC",]

ano  captura porto
3 2003 25      SC   
4 2004 32      SC

3- dados da captura >20


In [136]:
subset(dados, dados$captura > 20)

ano  captura porto
1 2001 26      SP   
3 2003 25      SC   
4 2004 32      SC

In [145]:
dados[dados$captura > 20, "captura"]

[1] 26 25 32 NA

4- dados da captura >25 e seja em SP

In [138]:
subset(dados, dados$captura > 25 & dados$porto=="SP")

ano  captura porto
1 2001 26      SP

In [146]:
dados[dados$captura > 25 & dados$porto == "SP",]

ano  captura porto
1 2001 26      SP